export const COLUMNS = [
  {
    title: "Name",
    dataIndex: "Name",
    width: "20%",
    sorter: (a, b) => {
      return a.Name.props["data-value"].localeCompare(
        b.Name.props["data-value"]
      );
    },
  },
  {
    title: "Classification",
    dataIndex: "Classification",
    sorter: (a, b) => a.Classification.localeCompare(b.Classification),
    width: "10%",
  },
  {
    title: "Country",
    dataIndex: "Country",
    width: "10%",
  },
  {
    title: "ISO CODE",
    dataIndex: "ISO CODE",
    width: "10%",
    render: (text, record) =>
      record.Linkiso === "x" ? (
        <div>{text}</div>
      ) : (
        <a
          href={record.Linkiso}
          className="text-blue-600"
          rel="noreferrer"
          target="_blank"
        >
          {text}
        </a>
      ),
  },
  {
    title: "GLOTTOCODE",
    dataIndex: "GLOTTOCODE",
    width: "10%",
    render: (text, record) => (
      <a
        href={record.linkglot}
        className="text-blue-600"
        rel="noreferrer"
        target="_blank"
      >
        {text}
      </a>
    ),
  },
  {
    title: "Latitude",
    dataIndex: "Latitude",
    width: "10%",
  },
  {
    title: "Longitude",
    dataIndex: "Longitude",
    width: "10%",
  },
];

export const DATA = [
  {
    Name: "Ejagham",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 5.54,
    Longitude: 8.91,
    "ISO CODE": "etu",
    Linkiso: "https://iso639-3.sil.org/code/etu",
    GLOTTOCODE: "ejag1239",
    linkglot: "https://glottolog.org/resource/languoid/id/ejag1239",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Efutop",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 5.92,
    Longitude: 8.35,
    "ISO CODE": "ofu",
    Linkiso: "https://iso639-3.sil.org/code/ofu",
    GLOTTOCODE: "efut1242",
    linkglot: "https://glottolog.org/resource/languoid/id/efut1242",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Balep",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.06,
    Longitude: 8.66,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "bale1253",
    linkglot: "https://glottolog.org/resource/languoid/id/bale1253",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Nde",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.22,
    Longitude: 8.47,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "ndee1242",
    linkglot: "https://glottolog.org/resource/languoid/id/ndee1242",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Nselle",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.2,
    Longitude: 8.54,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "sel1238",
    linkglot: "https://glottolog.org/resource/languoid/id/sel1238",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Abanyom",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.31,
    Longitude: 8.63,
    "ISO CODE": "abm",
    Linkiso: "https://iso639-3.sil.org/code/abm",
    GLOTTOCODE: "aban1242",
    linkglot: "https://glottolog.org/resource/languoid/id/aban1242",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Nkim",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.6,
    Longitude: 8.77,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "nkem1243",
    linkglot: "https://glottolog.org/resource/languoid/id/nkem1243",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Nnam",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.31,
    Longitude: 8.49,
    "ISO CODE": "nbp",
    Linkiso: "https://iso639-3.sil.org/code/nbp",
    GLOTTOCODE: "nnam1238",
    linkglot: "https://glottolog.org/resource/languoid/id/nnam1238",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Ekajuk",
    Classification: "Ekoid",
    Country: "Nigeria",
    Latitude: 6.46,
    Longitude: 8.55,
    "ISO CODE": "eka",
    Linkiso: "https://iso639-3.sil.org/code/eka",
    GLOTTOCODE: "ekaj1238",
    linkglot: "https://glottolog.org/resource/languoid/id/ekaj1238",
    source: "Blench, Roger. Unpublished. Comparative Ekoid.",
  },
  {
    Name: "Mbe",
    Classification: "Ekoid",
    Country: "Cameroon",
    Latitude: 6.26,
    Longitude: 11.09,
    "ISO CODE": "mfo",
    Linkiso: "https://iso639-3.sil.org/code/mfo",
    GLOTTOCODE: "mbee1249",
    linkglot: "https://glottolog.org/resource/languoid/id/mbee1249",
    source: "Blench, Roger. Unpublished. Mbe-English wordlist.",
  },
  {
    Name: "Tikar",
    Classification: "Ekoid",
    Country: "Cameroon",
    Latitude: 5.87,
    Longitude: 11.61,
    "ISO CODE": "tik",
    Linkiso: "https://iso639-3.sil.org/code/tik",
    GLOTTOCODE: "tika1246",
    linkglot: "https://glottolog.org/resource/languoid/id/tika1246",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Esimbi",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.5,
    Longitude: 9.87,
    "ISO CODE": "ags",
    Linkiso: "https://iso639-3.sil.org/code/ags",
    GLOTTOCODE: "esim1238",
    linkglot: "https://glottolog.org/resource/languoid/id/esim1238",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Tiv",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 7.5,
    Longitude: 8.8,
    "ISO CODE": "tiv",
    Linkiso: "https://iso639-3.sil.org/code/tiv",
    GLOTTOCODE: "tivv1240",
    linkglot: "https://glottolog.org/resource/languoid/id/tivv1240",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Afi",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.84,
    Longitude: 10.97,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "aman1261",
    linkglot: "https://glottolog.org/resource/languoid/id/aman1261",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Kamino",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.78,
    Longitude: 10.95,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "kami1257",
    linkglot: "https://glottolog.org/resource/languoid/id/kami1257",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Ugare",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.33,
    Longitude: 9.87,
    "ISO CODE": "iyo",
    Linkiso: "https://iso639-3.sil.org/code/iyo",
    GLOTTOCODE: "mesa1245",
    linkglot: "https://glottolog.org/resource/languoid/id/mesa1245",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Oliti",
    Classification: "Central_Tivoid",
    Country: "Cameroon",
    Latitude: 6.54,
    Longitude: 9.5,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "olit1238",
    linkglot: "https://glottolog.org/resource/languoid/id/olit1238",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Evand",
    Classification: "Central_Tivoid",
    Country: "Cameroon",
    Latitude: 6.35,
    Longitude: 9.46,
    "ISO CODE": "bzz",
    Linkiso: "https://iso639-3.sil.org/code/bzz",
    GLOTTOCODE: "evan1238",
    linkglot: "https://glottolog.org/resource/languoid/id/evan1238",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Caka-Batanga",
    Classification: "Central_Tivoid",
    Country: "Cameroon",
    Latitude: 6.27,
    Longitude: 9.78,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "bata1286",
    linkglot: "https://glottolog.org/resource/languoid/id/bata1286",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Ipulo",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.29,
    Longitude: 9.65,
    "ISO CODE": "ass",
    Linkiso: "https://iso639-3.sil.org/code/ass",
    GLOTTOCODE: "ipul1238",
    linkglot: "https://glottolog.org/resource/languoid/id/ipul1238",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Olulu",
    Classification: "Tivoid",
    Country: "Cameroon",
    Latitude: 6.35,
    Longitude: 9.67,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "olul1247",
    linkglot: "https://glottolog.org/resource/languoid/id/olul1247",
    source:
      "Blench, Roger. 2011. The Tivoid Languages: Classification and Comparative Wordlist. 16.",
  },
  {
    Name: "Koshin",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.58,
    Longitude: 10.3,
    "ISO CODE": "kid",
    Linkiso: "https://iso639-3.sil.org/code/kid",
    GLOTTOCODE: "kosh1246",
    linkglot: "https://glottolog.org/resource/languoid/id/kosh1246",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Noni",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.37,
    Longitude: 10.57,
    "ISO CODE": "nhu",
    Linkiso: "https://iso639-3.sil.org/code/nhu",
    GLOTTOCODE: "noon1243",
    linkglot: "https://glottolog.org/resource/languoid/id/noon1243",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Nchanti",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.51,
    Longitude: 10.53,
    "ISO CODE": "ncr",
    Linkiso: "https://iso639-3.sil.org/code/ncr",
    GLOTTOCODE: "ncan1245",
    linkglot: "https://glottolog.org/resource/languoid/id/ncan1245",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Abar",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.58,
    Longitude: 10.23,
    "ISO CODE": "mij",
    Linkiso: "https://iso639-3.sil.org/code/mij",
    GLOTTOCODE: "abar1238",
    linkglot: "https://glottolog.org/resource/languoid/id/abar1238",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Missong",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.6,
    Longitude: 10.23,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "miss1255",
    linkglot: "https://glottolog.org/resource/languoid/id/miss1255",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Bu",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.6,
    Longitude: 10.27,
    "ISO CODE": " jid",
    Linkiso: "https://iso639-3.sil.org/code/ jid",
    GLOTTOCODE: "buuu1244",
    linkglot: "https://glottolog.org/resource/languoid/id/buuu1244",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Misaje",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.63,
    Longitude: 10.59,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "x",
    linkglot: "x",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Akweto",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.63,
    Longitude: 10.6,
    "ISO CODE": "asj",
    Linkiso: "https://iso639-3.sil.org/code/asj",
    GLOTTOCODE: "nsar1238",
    linkglot: "https://glottolog.org/resource/languoid/id/nsar1238",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Menkaf",
    Classification: "Beboid",
    Country: "Cameroon",
    Latitude: 6.6,
    Longitude: 10.17,
    "ISO CODE": "mff",
    Linkiso: "https://iso639-3.sil.org/code/mff",
    GLOTTOCODE: "naki1238",
    linkglot: "https://glottolog.org/resource/languoid/id/naki1238",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Bebe Jatto",
    Classification: "Jatto_Beboid",
    Country: "Cameroon",
    Latitude: 6.75,
    Longitude: 10.56,
    "ISO CODE": "bzv",
    Linkiso: "https://iso639-3.sil.org/code/bzv",
    GLOTTOCODE: "bebe1250",
    linkglot: "https://glottolog.org/resource/languoid/id/bebe1250",
    source:
      "Hamm, Cameron, Jason Diller, Kari Jordan-Diller & Ferdinand Assako a Tiati. 2001. A rapid appraisal survey of Western Beboid languages (Menchum Division, Northwest Province). SIL International 14.40.",
  },
  {
    Name: "Kenyang",
    Classification: "Mamfe",
    Country: "Cameroon",
    Latitude: 5.58,
    Longitude: 9.56,
    "ISO CODE": "ken",
    Linkiso: "https://iso639-3.sil.org/code/ken",
    GLOTTOCODE: "keny1279",
    linkglot: "https://glottolog.org/resource/languoid/id/keny1279",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Mbembe",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 6.98,
    Longitude: 10.71,
    "ISO CODE": "nza",
    Linkiso: "https://iso639-3.sil.org/code/nza",
    GLOTTOCODE: "tigo1236",
    linkglot: "https://glottolog.org/resource/languoid/id/tigo1236",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Yukuben",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 6.92,
    Longitude: 9.98,
    "ISO CODE": "ybl",
    Linkiso: "https://iso639-3.sil.org/code/ybl",
    GLOTTOCODE: "yuku1243",
    linkglot: "https://glottolog.org/resource/languoid/id/yuku1243",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Kutep",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 7.07,
    Longitude: 10.09,
    "ISO CODE": "kub",
    Linkiso: "https://iso639-3.sil.org/code/kub",
    GLOTTOCODE: "kute1248",
    linkglot: "https://glottolog.org/resource/languoid/id/kute1248",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Kente",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 7.59,
    Longitude: 10.17,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "kent1256",
    linkglot: "https://glottolog.org/resource/languoid/id/kent1256",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Icen",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 7.14,
    Longitude: 10.35,
    "ISO CODE": "ich",
    Linkiso: "https://iso639-3.sil.org/code/ich",
    GLOTTOCODE: "etky1238",
    linkglot: "https://glottolog.org/resource/languoid/id/etky1238",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Ashuku",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 7.04,
    Longitude: 10.58,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "ashu1243",
    linkglot: "https://glottolog.org/resource/languoid/id/ashu1243",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Jiru",
    Classification: "Jukunoid",
    Country: "Cameroon",
    Latitude: 8.64,
    Longitude: 10.59,
    "ISO CODE": "jrr",
    Linkiso: "https://iso639-3.sil.org/code/jrr",
    GLOTTOCODE: "jiru1238",
    linkglot: "https://glottolog.org/resource/languoid/id/jiru1238",
    source:
      "Shimizu, K. 1971. Comparative Jukunoid: an introductory survey: University of Ibadan.",
  },
  {
    Name: "Kom",
    Classification: "Grassfields_Ring_Center",
    Country: "Cameroon",
    Latitude: 6.26,
    Longitude: 10.33,
    "ISO CODE": "bkm",
    Linkiso: "https://iso639-3.sil.org/code/bkm",
    GLOTTOCODE: "komc1235",
    linkglot: "https://glottolog.org/resource/languoid/id/komc1235",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Oku",
    Classification: "Grassfields_Ring_Center",
    Country: "Cameroon",
    Latitude: 6.24,
    Longitude: 10.51,
    "ISO CODE": "oku",
    Linkiso: "https://iso639-3.sil.org/code/oku",
    GLOTTOCODE: "okuu1243",
    linkglot: "https://glottolog.org/resource/languoid/id/okuu1243",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Babanki",
    Classification: "Grassfields_Ring_Center",
    Country: "Cameroon",
    Latitude: 5.98,
    Longitude: 10.29,
    "ISO CODE": "bbk",
    Linkiso: "https://iso639-3.sil.org/code/bbk",
    GLOTTOCODE: "baba1266",
    linkglot: "https://glottolog.org/resource/languoid/id/baba1266",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bum",
    Classification: "Grassfields_Ring_Center",
    Country: "Cameroon",
    Latitude: 6.49,
    Longitude: 10.42,
    "ISO CODE": "bmv",
    Linkiso: "https://iso639-3.sil.org/code/bmv",
    GLOTTOCODE: "bumm1238",
    linkglot: "https://glottolog.org/resource/languoid/id/bumm1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Aghem",
    Classification: "Grassfields_Ring_West",
    Country: "Cameroon",
    Latitude: 6.39,
    Longitude: 10.08,
    "ISO CODE": "agq",
    Linkiso: "https://iso639-3.sil.org/code/agq",
    GLOTTOCODE: "aghe1239",
    linkglot: "https://glottolog.org/resource/languoid/id/aghe1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Weh",
    Classification: "Grassfields_Ring_West",
    Country: "Cameroon",
    Latitude: 6.46,
    Longitude: 10.12,
    "ISO CODE": "weh",
    Linkiso: "https://iso639-3.sil.org/code/weh",
    GLOTTOCODE: "wehh1238",
    linkglot: "https://glottolog.org/resource/languoid/id/wehh1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Isu",
    Classification: "Grassfields_Ring_West",
    Country: "Cameroon",
    Latitude: 6.63,
    Longitude: 9.99,
    "ISO CODE": "isu",
    Linkiso: "https://iso639-3.sil.org/code/isu",
    GLOTTOCODE: "isum1240",
    linkglot: "https://glottolog.org/resource/languoid/id/isum1240",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Zoa",
    Classification: "Grassfields_Ring_West",
    Country: "Cameroon",
    Latitude: 6.53,
    Longitude: 10.16,
    "ISO CODE": "zhw",
    Linkiso: "https://iso639-3.sil.org/code/zhw",
    GLOTTOCODE: "zhoa1238",
    linkglot: "https://glottolog.org/resource/languoid/id/zhoa1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Kumfutu",
    Classification: "Grassfields_Ring_West",
    Country: "Cameroon",
    Latitude: 6.48,
    Longitude: 10.2,
    "ISO CODE": "kfn",
    Linkiso: "https://iso639-3.sil.org/code/kfn",
    GLOTTOCODE: "kukk1239",
    linkglot: "https://glottolog.org/resource/languoid/id/kukk1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Babunɡo",
    Classification: "Grassfields_Ring_South",
    Country: "Cameroon",
    Latitude: 6.11,
    Longitude: 10.41,
    "ISO CODE": "bav",
    Linkiso: "https://iso639-3.sil.org/code/bav",
    GLOTTOCODE: "veng1238",
    linkglot: "https://glottolog.org/resource/languoid/id/veng1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Babessi",
    Classification: "Grassfields_Ring_South",
    Country: "Cameroon",
    Latitude: 6.07,
    Longitude: 10.6,
    "ISO CODE": "bse",
    Linkiso: "https://iso639-3.sil.org/code/bse",
    GLOTTOCODE: "wush1238",
    linkglot: "https://glottolog.org/resource/languoid/id/wush1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bamessing",
    Classification: "Grassfields_Ring_South",
    Country: "Cameroon",
    Latitude: 6.02,
    Longitude: 10.41,
    "ISO CODE": "ndb",
    Linkiso: "https://iso639-3.sil.org/code/ndb",
    GLOTTOCODE: "kens1251",
    linkglot: "https://glottolog.org/resource/languoid/id/kens1251",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Lamso",
    Classification: "Ring_East",
    Country: "Cameroon",
    Latitude: 6.4,
    Longitude: 11.07,
    "ISO CODE": "lns",
    Linkiso: "https://iso639-3.sil.org/code/lns",
    GLOTTOCODE: "lamn1239",
    linkglot: "https://glottolog.org/resource/languoid/id/lamn1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Obang",
    Classification: "Menchum",
    Country: "Cameroon",
    Latitude: 6.28,
    Longitude: 10.03,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "oban1245",
    linkglot: "https://glottolog.org/resource/languoid/id/oban1245",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ngie",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 5.94,
    Longitude: 9.79,
    "ISO CODE": "ngj",
    Linkiso: "https://iso639-3.sil.org/code/ngj",
    GLOTTOCODE: "ngie1242",
    linkglot: "https://glottolog.org/resource/languoid/id/ngie1242",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Njen",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 5.75,
    Longitude: 9.9,
    "ISO CODE": "njj",
    Linkiso: "https://iso639-3.sil.org/code/njj",
    GLOTTOCODE: "njen1238",
    linkglot: "https://glottolog.org/resource/languoid/id/njen1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Moghamo",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 6.11,
    Longitude: 9.97,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mogh1246",
    linkglot: "https://glottolog.org/resource/languoid/id/mogh1246",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ngembu",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 5.9,
    Longitude: 10.09,
    "ISO CODE": "nbv",
    Linkiso: "https://iso639-3.sil.org/code/nbv",
    GLOTTOCODE: "ngam1267",
    linkglot: "https://glottolog.org/resource/languoid/id/ngam1267",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Oshie",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 6.05,
    Longitude: 9.83,
    "ISO CODE": "nsh",
    Linkiso: "https://iso639-3.sil.org/code/nsh",
    GLOTTOCODE: "ngos1238",
    linkglot: "https://glottolog.org/resource/languoid/id/ngos1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ngwaw",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 6.18,
    Longitude: 9.84,
    "ISO CODE": "ngn",
    Linkiso: "https://iso639-3.sil.org/code/ngn",
    GLOTTOCODE: "ngwo1241",
    linkglot: "https://glottolog.org/resource/languoid/id/ngwo1241",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Mundumi",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 6.14,
    Longitude: 9.97,
    "ISO CODE": "mnf",
    Linkiso: "https://iso639-3.sil.org/code/mnf",
    GLOTTOCODE: "mund1327",
    linkglot: "https://glottolog.org/resource/languoid/id/mund1327",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Menemo",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 6.11,
    Longitude: 9.97,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mene1239",
    linkglot: "https://glottolog.org/resource/languoid/id/mene1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ngie-Angong",
    Classification: "Grassfields_Momo",
    Country: "Cameroon",
    Latitude: 5.97,
    Longitude: 9.67,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "meng1265",
    linkglot: "https://glottolog.org/resource/languoid/id/meng1265",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bangang",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.61,
    Longitude: 10.13,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "bang1358",
    linkglot: "https://glottolog.org/resource/languoid/id/bang1358",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Fefe",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.18,
    Longitude: 10.14,
    "ISO CODE": "fmp",
    Linkiso: "https://iso639-3.sil.org/code/fmp",
    GLOTTOCODE: "fefe1239",
    linkglot: "https://glottolog.org/resource/languoid/id/fefe1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Fotouni",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.18,
    Longitude: 10.14,
    "ISO CODE": "fmp",
    Linkiso: "https://iso639-3.sil.org/code/fmp",
    GLOTTOCODE: "fefe1239",
    linkglot: "https://glottolog.org/resource/languoid/id/fefe1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bandjoun",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.4,
    Longitude: 10.35,
    "ISO CODE": "bbj",
    Linkiso: "https://iso639-3.sil.org/code/bbj",
    GLOTTOCODE: "ghom1247",
    linkglot: "https://glottolog.org/resource/languoid/id/ghom1247",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bafou",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.47,
    Longitude: 10.02,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "bafo1236",
    linkglot: "https://glottolog.org/resource/languoid/id/bafo1236",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bangangte",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.14,
    Longitude: 10.52,
    "ISO CODE": "byv",
    Linkiso: "https://iso639-3.sil.org/code/byv",
    GLOTTOCODE: "medu1238",
    linkglot: "https://glottolog.org/resource/languoid/id/medu1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Baham",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.33,
    Longitude: 10.39,
    "ISO CODE": "xmg",
    Linkiso: "https://iso639-3.sil.org/code/xmg",
    GLOTTOCODE: "meng1264",
    linkglot: "https://glottolog.org/resource/languoid/id/meng1264",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Fondjomekwet",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.26,
    Longitude: 10.15,
    "ISO CODE": "fmp",
    Linkiso: "https://iso639-3.sil.org/code/fmp",
    GLOTTOCODE: "fefe1239",
    linkglot: "https://glottolog.org/resource/languoid/id/fefe1239",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Batcha",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.11,
    Longitude: 10.32,
    "ISO CODE": "nnh",
    Linkiso: "https://iso639-3.sil.org/code/nnh",
    GLOTTOCODE: "ngie1241",
    linkglot: "https://glottolog.org/resource/languoid/id/ngie1241",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Batoufam",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.26,
    Longitude: 10.46,
    "ISO CODE": "nnz",
    Linkiso: "https://iso639-3.sil.org/code/nnz",
    GLOTTOCODE: "ndan1241",
    linkglot: "https://glottolog.org/resource/languoid/id/ndan1241",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bali/Mungaka",
    Classification: "Grassfields_EG_Nun",
    Country: "Cameroon",
    Latitude: 5.9,
    Longitude: 10.03,
    "ISO CODE": "mhk",
    Linkiso: "https://iso639-3.sil.org/code/mhk",
    GLOTTOCODE: "mung1266",
    linkglot: "https://glottolog.org/resource/languoid/id/mung1266",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bamun",
    Classification: "Grassfields_EG_Nun",
    Country: "Cameroon",
    Latitude: 5.49,
    Longitude: 10.85,
    "ISO CODE": "bvm",
    Linkiso: "https://iso639-3.sil.org/code/bvm",
    GLOTTOCODE: "bamu1253",
    linkglot: "https://glottolog.org/resource/languoid/id/bamu1253",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Baba",
    Classification: "Grassfields_EG_Nun",
    Country: "Cameroon",
    Latitude: 6.11,
    Longitude: 10.52,
    "ISO CODE": "bbw",
    Linkiso: "https://iso639-3.sil.org/code/bbw",
    GLOTTOCODE: "baba1264",
    linkglot: "https://glottolog.org/resource/languoid/id/baba1264",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bambalang",
    Classification: "Grassfields_EG_Nun",
    Country: "Cameroon",
    Latitude: 5.86,
    Longitude: 10.54,
    "ISO CODE": "bmo",
    Linkiso: "https://iso639-3.sil.org/code/bmo",
    GLOTTOCODE: "bamb1265",
    linkglot: "https://glottolog.org/resource/languoid/id/bamb1265",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Nkwen",
    Classification: "Grassfields_EG_Ngemba",
    Country: "Cameroon",
    Latitude: 6.03,
    Longitude: 10.24,
    "ISO CODE": "mfd",
    Linkiso: "https://iso639-3.sil.org/code/mfd",
    GLOTTOCODE: "mend1261",
    linkglot: "https://glottolog.org/resource/languoid/id/mend1261",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bafut",
    Classification: "Grassfields_EG_Ngemba",
    Country: "Cameroon",
    Latitude: 6.14,
    Longitude: 10.12,
    "ISO CODE": "bfd",
    Linkiso: "https://iso639-3.sil.org/code/bfd",
    GLOTTOCODE: "bafu1246",
    linkglot: "https://glottolog.org/resource/languoid/id/bafu1246",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Mankon",
    Classification: "Grassfields_EG_Ngemba",
    Country: "Cameroon",
    Latitude: 5.96,
    Longitude: 10.15,
    "ISO CODE": "nge",
    Linkiso: "https://iso639-3.sil.org/code/nge",
    GLOTTOCODE: "ngem1255",
    linkglot: "https://glottolog.org/resource/languoid/id/ngem1255",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Awing",
    Classification: "Grassfields_EG_Ngemba",
    Country: "Cameroon",
    Latitude: 5.88,
    Longitude: 10.26,
    "ISO CODE": "azo",
    Linkiso: "https://iso639-3.sil.org/code/azo",
    GLOTTOCODE: "awin1248",
    linkglot: "https://glottolog.org/resource/languoid/id/awin1248",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ngwe",
    Classification: "Grassfields_EG_Bamileke",
    Country: "Cameroon",
    Latitude: 5.5,
    Longitude: 9.9,
    "ISO CODE": "new",
    Linkiso: "https://iso639-3.sil.org/code/new",
    GLOTTOCODE: "ngwe1238",
    linkglot: "https://glottolog.org/resource/languoid/id/ngwe1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Limbum",
    Classification: "Grassfields_EG_North",
    Country: "Cameroon",
    Latitude: 6.59,
    Longitude: 10.98,
    "ISO CODE": "lmp",
    Linkiso: "https://iso639-3.sil.org/code/lmp",
    GLOTTOCODE: "limb1268",
    linkglot: "https://glottolog.org/resource/languoid/id/limb1268",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Adere",
    Classification: "Grassfields_EG_North",
    Country: "Cameroon",
    Latitude: 6.89,
    Longitude: 10.76,
    "ISO CODE": "add",
    Linkiso: "https://iso639-3.sil.org/code/add",
    GLOTTOCODE: "dzod1238",
    linkglot: "https://glottolog.org/resource/languoid/id/dzod1238",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Ndemli",
    Classification: "Grassfields",
    Country: "Cameroon",
    Latitude: 4.58,
    Longitude: 10.22,
    "ISO CODE": "nml",
    Linkiso: "https://iso639-3.sil.org/code/nml",
    GLOTTOCODE: "ndem1249",
    linkglot: "https://glottolog.org/resource/languoid/id/ndem1249",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "Bwazza",
    Classification: "Jarawan",
    Country: "Cameroon or Nigeria?",
    Latitude: 9.68,
    Longitude: 12.19,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "bwaz1238",
    linkglot: "https://glottolog.org/resource/languoid/id/bwaz1238",
    source:
      "Blench R (2006) Jarawan Bantu: New Data and Its Relation to Bantu.  (Mallam Dendo, Cambridge), p 18.",
  },
  {
    Name: "Mbula",
    Classification: "Jarawan",
    Country: "Nigeria",
    Latitude: 9.64,
    Longitude: 12.1,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mbul1261",
    linkglot: "https://glottolog.org/resource/languoid/id/mbul1261",
    source:
      "Blench R (2006) Jarawan Bantu: New Data and Its Relation to Bantu.  (Mallam Dendo, Cambridge), p 18.",
  },
  {
    Name: "Bile",
    Classification: "Jarawan",
    Country: "Nigeria",
    Latitude: 9.05,
    Longitude: 11.87,
    "ISO CODE": "bil",
    Linkiso: "https://iso639-3.sil.org/code/bil",
    GLOTTOCODE: "bile1244",
    linkglot: "https://glottolog.org/resource/languoid/id/bile1244",
    source:
      "Blench R (2006) Jarawan Bantu: New Data and Its Relation to Bantu.  (Mallam Dendo, Cambridge), p 18.",
  },
  {
    Name: "Kulung",
    Classification: "Jarawan",
    Country: "Nigeria",
    Latitude: 9.46,
    Longitude: 10.97,
    "ISO CODE": "bbu",
    Linkiso: "https://iso639-3.sil.org/code/bbu",
    GLOTTOCODE: "kulu1255",
    linkglot: "https://glottolog.org/resource/languoid/id/kulu1255",
    source:
      "Blench R (2006) Jarawan Bantu: New Data and Its Relation to Bantu.  (Mallam Dendo, Cambridge), p 18.",
  },
  {
    Name: "Duguri",
    Classification: "Jarawan",
    Country: "Nigeria",
    Latitude: 9.61,
    Longitude: 10.87,
    "ISO CODE": "dbm",
    Linkiso: "https://iso639-3.sil.org/code/dbm",
    GLOTTOCODE: "dugu1249",
    linkglot: "https://glottolog.org/resource/languoid/id/dugu1249",
    source:
      "Blench R (2006) Jarawan Bantu: New Data and Its Relation to Bantu.  (Mallam Dendo, Cambridge), p 18.",
  },
  {
    Name: "A11_Londo",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 5.1,
    Longitude: 9.29,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "lond1243",
    linkglot: "https://glottolog.org/resource/languoid/id/lond1243",
    source:
      "Kuperus J (1978) Les classes nominales du Londo ; langue bantoue du sud-ouest du Cameroun (Guthrie A11). (Rapport préliminaire):33.",
  },
  {
    Name: "A121_Mbonge",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.78,
    Longitude: 9.2,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mbon1250",
    linkglot: "https://glottolog.org/resource/languoid/id/mbon1250",
    source:
      "Friesen DT (2002) Oroko orthography development: Linguistic and sociolinguistic factors. Master of Arts (University of North Dakota).",
  },
  {
    Name: "A122_Bakundu",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.81,
    Longitude: 9.1,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "baku1261",
    linkglot: "https://glottolog.org/resource/languoid/id/baku1261",
    source:
      "Grassfields Bantu Working Group including Jean-Marie Hombert and Larry Hyman",
  },
  {
    Name: "A15_Manenguba",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.98,
    Longitude: 9.67,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mane1268",
    linkglot: "https://glottolog.org/resource/languoid/id/mane1268",
    source:
      "Hedinger R (1987) The Manenguba languages (Bantu A. 15, Mbo cluster) of Cameroon (School of Oriental and African Studies (SOAS), London) p 306.",
  },
  {
    Name: "A15C_Akossi",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 5.3,
    Longitude: 9.55,
    "ISO CODE": "bss",
    Linkiso: "https://iso639-3.sil.org/code/bss",
    GLOTTOCODE: "akoo1248",
    linkglot: "https://glottolog.org/resource/languoid/id/akoo1248",
    source:
      "Hedinger R (1987) The Manenguba languages (Bantu A. 15, Mbo cluster) of Cameroon (School of Oriental and African Studies (SOAS), London) p 306.",
  },
  {
    Name: "A22_Bakweri ",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.25,
    Longitude: 9.35,
    "ISO CODE": "bri",
    Linkiso: "https://iso639-3.sil.org/code/bri",
    GLOTTOCODE: "mokp1239",
    linkglot: "https://glottolog.org/resource/languoid/id/mokp1239",
    source:
      "Connell B (1997) Mokpe (Bakweri), Available on CBOLD http://www.cbold.ish-lyon.cnrs.fr/ (last visit: 24-04-2011).",
  },
  {
    Name: "A24_Duala",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.2,
    Longitude: 9.55,
    "ISO CODE": "dua",
    Linkiso: "https://iso639-3.sil.org/code/dua",
    GLOTTOCODE: "dual1243",
    linkglot: "https://glottolog.org/resource/languoid/id/dual1243",
    source:
      "Helmlinger P (1972) Dictionnaire duala-français, suivi d'un lexique français-duala (Klincksieck, Langues et Littératures de l'Afrique noire 9, Paris) p 665.",
  },
  {
    Name: "A27_Malimba",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 3.75,
    Longitude: 9.6,
    "ISO CODE": "mzd",
    Linkiso: "https://iso639-3.sil.org/code/mzd",
    GLOTTOCODE: "mali1280",
    linkglot: "https://glottolog.org/resource/languoid/id/mali1280",
    source:
      "Lamberty M (2002) A rapid appraisal survey of the Abo and Barombi speech communities, South West and Littoral Provinces, Cameroon. SIL International:28.",
  },
  {
    Name: "A31_Bubi",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 3.4,
    Longitude: 8.65,
    "ISO CODE": "bvb",
    Linkiso: "https://iso639-3.sil.org/code/bvb",
    GLOTTOCODE: "bube1242",
    linkglot: "https://glottolog.org/resource/languoid/id/bube1242",
    source:
      "Rurangwa IM (1989) Enquête linguistique sur le bubi, langue bantu insulaire de Guinée Équatoriale. Actes du Colloque international “Les peuples bantu. Migrations, Expansion et Identité culturelle” Libreville 1-6 avril 1985, Tome I, ed Obenga T (Libreville: CICIBA; Paris: L’Harmattan), pp 76-102.",
  },
  {
    Name: "A33a_Yasa",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 2.45,
    Longitude: 9.85,
    "ISO CODE": "yko",
    Linkiso: "https://iso639-3.sil.org/code/yko",
    GLOTTOCODE: "yasa1242",
    linkglot: "https://glottolog.org/resource/languoid/id/yasa1242",
    source:
      "Blench R (2010) Yasa-French wordlist. Available on http://www.rogerblench.info/Language/Niger-Congo//Bantu/A30/Yasa/Yasa-French%20wordlist.pdf ",
  },
  {
    Name: "A34_Benga",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 1.25,
    Longitude: 9.4,
    "ISO CODE": "bng",
    Linkiso: "https://iso639-3.sil.org/code/bng",
    GLOTTOCODE: "beng1282",
    linkglot: "https://glottolog.org/resource/languoid/id/beng1282",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "A41_Barombi-Kang",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.55,
    Longitude: 9.35,
    "ISO CODE": "bbi",
    Linkiso: "https://iso639-3.sil.org/code/bbi",
    GLOTTOCODE: "baro1252",
    linkglot: "https://glottolog.org/resource/languoid/id/baro1252",
    source:
      "Lamberty M (2002) A rapid appraisal survey of the Abo and Barombi speech communities, South West and Littoral Provinces, Cameroon. SIL International:28.",
  },
  {
    Name: "A42_Abo",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.4,
    Longitude: 9.6,
    "ISO CODE": "abb",
    Linkiso: "https://iso639-3.sil.org/code/abb",
    GLOTTOCODE: "bank1256",
    linkglot: "https://glottolog.org/resource/languoid/id/bank1256",
    source:
      "Lamberty M (2002) A rapid appraisal survey of the Abo and Barombi speech communities, South West and Littoral Provinces, Cameroon. SIL International:28.",
  },
  {
    Name: "A43a_Basaa",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 5,
    Longitude: 10.2,
    "ISO CODE": "bas",
    Linkiso: "https://iso639-3.sil.org/code/bas",
    GLOTTOCODE: "basa1284",
    linkglot: "https://glottolog.org/resource/languoid/id/basa1284",
    source:
      "Collector: Gisèle Teil-Dautrey, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "A44_Tunen",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.7,
    Longitude: 10.9,
    "ISO CODE": "tvu",
    Linkiso: "https://iso639-3.sil.org/code/tvu",
    GLOTTOCODE: "tune1261",
    linkglot: "https://glottolog.org/resource/languoid/id/tune1261",
    source:
      "Dugast I (1967) Lexique de la langue Tunen (Parler des Banen du Sud-Ouest du Cameroun) (Klincksieck, Langues et littératures de l’Afrique noire, Paris) p 235.",
  },
  {
    Name: "A45_Nyokon",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.78,
    Longitude: 10.95,
    "ISO CODE": "nvo",
    Linkiso: "https://iso639-3.sil.org/code/nvo",
    GLOTTOCODE: "nyok1243",
    linkglot: "https://glottolog.org/resource/languoid/id/nyok1243",
    source:
      "Mous M & Breedveld A (1986) A dialectometrical study of some Bantu languages (A.40-A.60) of Cameroon. La méthode dialectométrique appliquée aux langues africaines, eds Guarisma G & Möhlig WJG (Dietrich Reimer Verlag, Berlin), pp 177-241.",
  },
  {
    Name: "A46_Nomaande",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.62,
    Longitude: 11.06,
    "ISO CODE": "lem",
    Linkiso: "https://iso639-3.sil.org/code/lem",
    GLOTTOCODE: "noma1260",
    linkglot: "https://glottolog.org/resource/languoid/id/noma1260",
    source:
      "Taylor C & Scruggs TR (2003) Lexique Nomaande-Français. SIL Electronic Survey Reports:24.",
  },
  {
    Name: "A462_Yambeta",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.74,
    Longitude: 11.03,
    "ISO CODE": "yat",
    Linkiso: "https://iso639-3.sil.org/code/yat",
    GLOTTOCODE: "yamb1252",
    linkglot: "https://glottolog.org/resource/languoid/id/yamb1252",
    source:
      "Mous M & Breedveld A (1986) A dialectometrical study of some Bantu languages (A.40-A.60) of Cameroon. La méthode dialectométrique appliquée aux langues africaines, eds Guarisma G & Möhlig WJG (Dietrich Reimer Verlag, Berlin), pp 177-241.",
  },
  {
    Name: "A51_Bafia_maja",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.83,
    Longitude: 11.17,
    "ISO CODE": "lfa",
    Linkiso: "https://iso639-3.sil.org/code/lfa",
    GLOTTOCODE: "lefa1242",
    linkglot: "https://glottolog.org/resource/languoid/id/lefa1242",
    source:
      "Bastin Y, Coupez A, & Mann M (1999) Continuity and divergence in the Bantu languages: perspectives from a lexicostatistic study (Musée Royal de l’Afrique Centrale (MRAC), Annales, Série in-8°, Sciences humaines 162, Tervuren) p 225.",
  },
  {
    Name: "A53_Bafia_rikpa",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 5,
    Longitude: 11.15,
    "ISO CODE": "ksf",
    Linkiso: "https://iso639-3.sil.org/code/ksf",
    GLOTTOCODE: "bafi1243",
    linkglot: "https://glottolog.org/resource/languoid/id/bafi1243",
    source:
      "Guarisma G (1969) Études bafia: phonologie, classes d'accord et lexique bafia-français (Société des Études Linguistiques et Anthropologiques de France (SELAF), Paris) p 123.",
  },
  {
    Name: "A601_Tuki",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.5,
    Longitude: 11.4,
    "ISO CODE": "bag",
    Linkiso: "https://iso639-3.sil.org/code/bag",
    GLOTTOCODE: "tuki1240",
    linkglot: "https://glottolog.org/resource/languoid/id/tuki1240",
    source:
      "Kongne Welaze J, Biteya M, Ilomo B, & Okalia G (2006) Lexique Tuki—Français avec index Français—Tuki. Association Nationale des Comités de Langues Camerounaises (ANACLAC):pp. 82.",
  },
  {
    Name: "A622_Nugunu ",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.6,
    Longitude: 11.3,
    "ISO CODE": "yas",
    Linkiso: "https://iso639-3.sil.org/code/yas",
    GLOTTOCODE: "nugu1242",
    linkglot: "https://glottolog.org/resource/languoid/id/nugu1242",
    source: "Robinson CDW (1979) Petit lexique gunu-français (SIL, Yaounde)",
  },
  {
    Name: "A63_Mangisa",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.45,
    Longitude: 11.45,
    "ISO CODE": "leo",
    Linkiso: "https://iso639-3.sil.org/code/leo",
    GLOTTOCODE: "leti1245",
    linkglot: "https://glottolog.org/resource/languoid/id/leti1245",
    source: "Anonymous (19--) SIL comparative African word list.",
  },
  {
    Name: "A71_Eton",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.25,
    Longitude: 11.45,
    "ISO CODE": "eto",
    Linkiso: "https://iso639-3.sil.org/code/eto",
    GLOTTOCODE: "eton1253",
    linkglot: "https://glottolog.org/resource/languoid/id/eton1253",
    source:
      "Van de Velde MLO (2008) A grammar of Eton (Mouton de Gruyter) p 428.",
  },
  {
    Name: "A72a_Ewondo",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.2,
    Longitude: 12.2,
    "ISO CODE": "ewo",
    Linkiso: "https://iso639-3.sil.org/code/ewo",
    GLOTTOCODE: "ewon1239",
    linkglot: "https://glottolog.org/resource/languoid/id/ewon1239",
    source: "Anonymous (1---) Lexique ewondo-français et français-ewondo",
  },
  {
    Name: "A74a_Bulu",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 2.95,
    Longitude: 10.85,
    "ISO CODE": "bum",
    Linkiso: "https://iso639-3.sil.org/code/bum",
    GLOTTOCODE: "bulu1251",
    linkglot: "https://glottolog.org/resource/languoid/id/bulu1251",
    source:
      "Alexandre P (1955) Manuel élémentaire de la langue bulu (Sud Cameroun) (Paris : Centre de Hautes Études d’Administration Musulmane (CHEAM)) p 231.",
  },
  {
    Name: "A75a_Fang_Bitam",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 2.08,
    Longitude: 11.49,
    "ISO CODE": "fan",
    Linkiso: "https://iso639-3.sil.org/code/fan",
    GLOTTOCODE: "fang1246",
    linkglot: "https://glottolog.org/resource/languoid/id/fang1246",
    source: "ALGAB, Collector: Pither Medjo Mve, Université Omar Bongo, Gabon",
  },
  {
    Name: "A81_Kwasio ",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 3.06,
    Longitude: 10.22,
    "ISO CODE": "nmg",
    Linkiso: "https://iso639-3.sil.org/code/nmg",
    GLOTTOCODE: "kwas1243",
    linkglot: "https://glottolog.org/resource/languoid/id/kwas1243",
    source: "Collector: Dan Duke, SIL - Cameroon",
  },
  {
    Name: "A83_Mekaa",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.17,
    Longitude: 12.52,
    "ISO CODE": "mcp",
    Linkiso: "https://iso639-3.sil.org/code/mcp",
    GLOTTOCODE: "maka1304",
    linkglot: "https://glottolog.org/resource/languoid/id/maka1304",
    source: "Collector: Daniel P. Heath, SIL - Cameroon",
  },
  {
    Name: "A85b_Bekwil_Makokou",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.56,
    Longitude: 12.83,
    "ISO CODE": "bkw",
    Linkiso: "https://iso639-3.sil.org/code/bkw",
    GLOTTOCODE: "bekw1242",
    linkglot: "https://glottolog.org/resource/languoid/id/bekw1242",
    source:
      "ALGAB, Collector: Marion Cheucle, Laboratoire Dynamique du Langage, Lyon ",
  },
  {
    Name: "A86c_Mpiemo",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 3.41,
    Longitude: 15.27,
    "ISO CODE": "mcx",
    Linkiso: "https://iso639-3.sil.org/code/mcx",
    GLOTTOCODE: "mpie1238",
    linkglot: "https://glottolog.org/resource/languoid/id/mpie1238",
    source:
      "Bouka L-Y (1993) Bekwel-Congo, Available on CBOLD http://www.cbold.ish-lyon.cnrs.fr/ last visit: 24-04-2011).",
  },
  {
    Name: "A91_Kwakum",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.8,
    Longitude: 13.5,
    "ISO CODE": "kwu",
    Linkiso: "https://iso639-3.sil.org/code/kwu",
    GLOTTOCODE: "kwak1266",
    linkglot: "https://glottolog.org/resource/languoid/id/kwak1266",
    source:
      "Belliard F (2007) Parlons kwàkúm (Editions L'Harmattan, Paris) p 241.",
  },
  {
    Name: "A93_Kako",
    Classification: "Bantu",
    Country: "Cameroon",
    Latitude: 4.71,
    Longitude: 13.9,
    "ISO CODE": "kkj",
    Linkiso: "https://iso639-3.sil.org/code/kkj",
    GLOTTOCODE: "kako1242",
    linkglot: "https://glottolog.org/resource/languoid/id/kako1242",
    source:
      "Ernst U (1991) Temps et aspect en kako. Tense and aspect in eight languages of Cameroon, eds Anderson SC & Comrie B (Summer Institute of Linguistics and the University of Texas at Arlington Publications in Linguistics, 99), pp 17-45.",
  },
  {
    Name: "B11a_Mpongwe",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.2,
    Longitude: 9.55,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mpon1255",
    linkglot: "https://glottolog.org/resource/languoid/id/mpon1255",
    source:
      "ALGAB, Collector: Patrick Mouguiama-Daouda, Université Omar Bongo, Gabon",
  },
  {
    Name: "B11b_Orungu",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.72,
    Longitude: 8.78,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "orun1242",
    linkglot: "https://glottolog.org/resource/languoid/id/orun1242",
    source:
      "ALGAB, Collectors: Odette Ambouroue and Mark Van de Velde, LLACAN Paris",
  },
  {
    Name: "B11c_Galwa",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.7,
    Longitude: 10.24,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "galw1238",
    linkglot: "https://glottolog.org/resource/languoid/id/galw1238",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B11d_Dyumba ",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.59,
    Longitude: 10.07,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "ajum1239",
    linkglot: "https://glottolog.org/resource/languoid/id/ajum1239",
    source:
      "ALGAB, Collectors: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon, Odette Ambouroue, LLACAN Paris and Mark Van de Velde, LLACAN Paris",
  },
  {
    Name: "B11F_Enenga",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.7,
    Longitude: 10.29,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "nen1239",
    linkglot: "https://glottolog.org/resource/languoid/id/nen1239",
    source:
      "ALGAB, Collectors: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon, Odette Ambouroue, LLACAN Paris and Mark Van de Velde, LLACAN Paris",
  },
  {
    Name: "B31_Tsogo",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.5,
    Longitude: 11.3,
    "ISO CODE": "tsv",
    Linkiso: "https://iso639-3.sil.org/code/tsv",
    GLOTTOCODE: "tsog1243",
    linkglot: "https://glottolog.org/resource/languoid/id/tsog1243",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B32_Kande",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.01,
    Longitude: 11.75,
    "ISO CODE": "kbs",
    Linkiso: "https://iso639-3.sil.org/code/kbs",
    GLOTTOCODE: "kand1300",
    linkglot: "https://glottolog.org/resource/languoid/id/kand1300",
    source:
      "ALGAB, Collectors: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon and Rebecca Grollemund, University of Reading",
  },
  {
    Name: "B301_Viya",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.21,
    Longitude: 10.65,
    "ISO CODE": "gev",
    Linkiso: "https://iso639-3.sil.org/code/gev",
    GLOTTOCODE: "eviy1235",
    linkglot: "https://glottolog.org/resource/languoid/id/eviy1235",
    source:
      "ALGAB, Collector: Lolke van der Veen, Laboratoire Dynamique du Langage, Lyon ",
  },
  {
    Name: "B302_Himba",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.48,
    Longitude: 11.54,
    "ISO CODE": "sbw",
    Linkiso: "https://iso639-3.sil.org/code/sbw",
    GLOTTOCODE: "simb1254",
    linkglot: "https://glottolog.org/resource/languoid/id/simb1254",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B304_Pinzi",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.93,
    Longitude: 11.22,
    "ISO CODE": "pic",
    Linkiso: "https://iso639-3.sil.org/code/pic",
    GLOTTOCODE: "pinj1243",
    linkglot: "https://glottolog.org/resource/languoid/id/pinj1243",
    source:
      "ALGAB, Collectors: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon, Lolke van der Veen, Laboratoire Dynamique du Langage, Lyon and Rebecca Grollemund, University of Reading",
  },
  {
    Name: "B305_Vove",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -1.1,
    Longitude: 12.3,
    "ISO CODE": "buw",
    Linkiso: "https://iso639-3.sil.org/code/buw",
    GLOTTOCODE: "bubi1250",
    linkglot: "https://glottolog.org/resource/languoid/id/bubi1250",
    source:
      "ALGAB, Collector: Lolke van der Veen, Laboratoire Dynamique du Langage, Lyon ",
  },
  {
    Name: "B21_Seki ",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.95,
    Longitude: 9.6,
    "ISO CODE": "syi",
    Linkiso: "https://iso639-3.sil.org/code/syi",
    GLOTTOCODE: "seki1238",
    linkglot: "https://glottolog.org/resource/languoid/id/seki1238",
    source:
      "ALGAB, Collector: Gilbert Puech, Laboratoire Dynamique du Langage, Lyon ",
  },
  {
    Name: "B22a_Kele",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.8,
    Longitude: 10.35,
    "ISO CODE": "keb",
    Linkiso: "https://iso639-3.sil.org/code/keb",
    GLOTTOCODE: "kele1257",
    linkglot: "https://glottolog.org/resource/languoid/id/kele1257",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B22b_Ngom ",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 1.3,
    Longitude: 14.15,
    "ISO CODE": "nra",
    Linkiso: "https://iso639-3.sil.org/code/nra",
    GLOTTOCODE: "ngom1270",
    linkglot: "https://glottolog.org/resource/languoid/id/ngom1270",
    source:
      "ALGAB, Collectors: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon and Gilbert Puech, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B22E_Mwesa",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 1.2,
    Longitude: 13.3,
    "ISO CODE": "x",
    Linkiso: "x",
    GLOTTOCODE: "mwes1234",
    linkglot: "https://glottolog.org/resource/languoid/id/mwes1234",
    source: "ALGAB, Collector: Pither Medjo Mve, Université Omar Bongo, Gabon",
  },
  {
    Name: "B23_Mbangwe",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -2.1,
    Longitude: 13.65,
    "ISO CODE": "zmn",
    Linkiso: "https://iso639-3.sil.org/code/zmn",
    GLOTTOCODE: "mban1268",
    linkglot: "https://glottolog.org/resource/languoid/id/mban1268",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B24_Wumbvu",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -2.3,
    Longitude: 12.25,
    "ISO CODE": "wum",
    Linkiso: "https://iso639-3.sil.org/code/wum",
    GLOTTOCODE: "wumb1242",
    linkglot: "https://glottolog.org/resource/languoid/id/wumb1242",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B25_Kota",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.01,
    Longitude: 12.8,
    "ISO CODE": "koq",
    Linkiso: "https://iso639-3.sil.org/code/koq",
    GLOTTOCODE: "kota1274",
    linkglot: "https://glottolog.org/resource/languoid/id/kota1274",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B251_Shake",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.25,
    Longitude: 11.75,
    "ISO CODE": "sak",
    Linkiso: "https://iso639-3.sil.org/code/sak",
    GLOTTOCODE: "sake1247",
    linkglot: "https://glottolog.org/resource/languoid/id/sake1247",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B252_Mahongwe",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.65,
    Longitude: 14,
    "ISO CODE": "mhb",
    Linkiso: "https://iso639-3.sil.org/code/mhb",
    GLOTTOCODE: "maho1248",
    linkglot: "https://glottolog.org/resource/languoid/id/maho1248",
    source: "ALGAB, Collector: Pither Medjo Mve, Université Omar Bongo, Gabon",
  },
  {
    Name: "B201_Ndasa",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -3,
    Longitude: 13.6,
    "ISO CODE": "nda",
    Linkiso: "https://iso639-3.sil.org/code/nda",
    GLOTTOCODE: "ndas1238",
    linkglot: "https://glottolog.org/resource/languoid/id/ndas1238",
    source:
      "ALGAB, Collector: Jean-Marie Hombert, Laboratoire Dynamique du Langage, Lyon",
  },
  {
    Name: "B202_Sigu",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: -0.7,
    Longitude: 12.55,
    "ISO CODE": "sxe",
    Linkiso: "https://iso639-3.sil.org/code/sxe",
    GLOTTOCODE: "sigh1238",
    linkglot: "https://glottolog.org/resource/languoid/id/sigh1238",
    source:
      "Ibouily D (2005) Esquisse phonologique et morphologique du Lisi:wu (Langue Bantu du Gabon de sigle B 27). Mémoire de Maîtrise (Université Omar Bongo, Gabon).",
  },
  {
    Name: "B203_Samaye",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.96,
    Longitude: 13.7,
    "ISO CODE": "syx",
    Linkiso: "https://iso639-3.sil.org/code/syx",
    GLOTTOCODE: "osam1235",
    linkglot: "https://glottolog.org/resource/languoid/id/osam1235",
    source:
      "Mokrani S (2005) Elément nouveaux en vue de la description de la langue Samaye (B25) - Elements de phonologie et de morphologie. Mémoire de Master 2 (Université Lyon 2).",
  },
  {
    Name: "B204_Ndambomo_Li",
    Classification: "Bantu",
    Country: "Gabon",
    Latitude: 0.68,
    Longitude: 12.65,
    "ISO CODE": "nxo",
    Linkiso: "https://iso639-3.sil.org/code/nxo",
    GLOTTOCODE: "ndam1254",
    linkglot: "https://glottolog.org/resource/languoid/id/ndam1254",
    source: "ALGAB, Collector: Pither Medjo Mve, Université Omar Bongo, Gabon",
  },
];
